### ISSUE TITLE
rake -T failed, cannot load such file bundler/setup

### ISSUE THREAD

**Issue by black-snow** [lslezak/build-rake#9]
Hi,

after updating atom to 1.13.0 the rake plugin fails to load.

```
Command failed: rake -T
rake aborted!
cannot load such file -- bundler/setup
/Users/Shared/xxx/server/config/boot.rb:3:in `<top (required)>'
/Users/Shared/xxx/server/config/application.rb:1:in `<top (required)>'
/Users/Shared/xxx/server/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

Stack Trace

Error: Command failed: rake -T
rake aborted!
cannot load such file -- bundler/setup
/Users/Shared/xxx/server/config/boot.rb:3:in `<top (required)>'
/Users/Shared/xxx/server/config/application.rb:1:in `<top (required)>'
/Users/Shared/xxx/server/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

I tried `bundle install` and updating bundler and `bundle exec rake rails:update:bin` but no fix so far. Any guesses?

This only happens right after starting atom. When hitting cmd+alt+t it loads the targets (after a while).

**Comment by black-snow** [comment]
Happens on another machine yet with atom 1.12.6, too.

**Comment by black-snow** [comment]
Guess I figured it out. The error is popping up when atom is starting into the settings pane (or any other non-project tab). This mostly happens after updating packages (for I'm hitting restart from the settings pane).

**Comment by anarchivist** [comment]
I'm still seeing the same thing on Atom 1.18.0:

```
Command failed: rake -T
rake aborted!
cannot load such file -- bundler/setup
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/config/boot.rb:3:in `<top (required)>'
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/config/application.rb:1:in `require_relative'
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/config/application.rb:1:in `<top (required)>'
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/Rakefile:4:in `require_relative'
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

Stack Trace

Error: Command failed: rake -T
rake aborted!
cannot load such file -- bundler/setup
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/config/boot.rb:3:in `<top (required)>'
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/config/application.rb:1:in `require_relative'
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/config/application.rb:1:in `<top (required)>'
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/Rakefile:4:in `require_relative'
/Users/matienzo/Documents/Code/sul-dlss/arclight-demo/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by edusantana** [comment]
For me it's working on atom `1.47.0, linux`
